# Generated by Django 5.0 on 2024-01-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=50)),
                ('pro_desc', models.CharField(max_length=50)),
                ('pro_img', models.ImageField(upload_to='img/')),
                ('pro_cat', models.CharField(choices=[('Carrara', 'Carrara'), ('Statuary', 'Statuary'), ('Calacatta', 'Calacatta'), ('Emperador', 'Emperador'), ('Crema Marfil', 'Crema Marfil')], max_length=30)),
            ],
        ),
    ]
